feat: Add a CodeZero Desktop app tutorial
c6o/docs pull request #121
Opened 2022-02-01 04:53 UTC by Canuckaholic

## Description

Used this for the UX user testing session.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Technical improvement or removal of technical debt. 
- [ ] Minor change: comments, documentation, trivial fixes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Unit Tests

Optional:

- [ ] Functional Tests
- [ ] Integration Tests

2022-02-03 00:05 UTC, conneryn commented on content/tutorials/desktop-app.md
> +apiVersion: system.codezero.io/v1alpha1
I'm not sure if we should highlight the actual contents of the development profile.

See proposed alternative text, or, we could show the CLI equivalent if we wanted?
`czctl teleport deployment sample-project-core -n sample-project -f ./env.sh`

2022-02-03 00:05 UTC, conneryn commented on content/tutorials/desktop-app.md
> +The Sample Project comes with an example Development Profile with just a single Teleport command:
```suggestion
The Sample Project comes with an example Development Profile called "teleport", which opens a basic teleport session to the `sample-project` namespace and exports the `sample-project-core` deployment's environment variables to the file `./env.sh`.
```

2022-02-03 00:16 UTC, Canuckaholic commented on content/tutorials/desktop-app.md
> +yarn start-frontend
I'm open to however we want to structure this. So perhaps this tutorial starts with something like "this tutorial assumes you have completed tutorials #1 and #2"?

2022-02-04 17:44 UTC, nsainaney commented on content/tutorials/desktop-app.md
> +Head over to the [CodeZero website](https://codezero.io/platform/desktop) and download the Desktop app for your platform. Run the installer.
This should be under Guides and by the time you come to the Tutorial, you can assume they have it installed

2022-02-07 18:08 UTC, nsainaney requested changes

2022-02-07 18:08 UTC, nsainaney commented on content/tutorials/desktop-app.md
> +### Set up the Sample Project
Make this document consistent with https://docs.codezero.io/#/tutorials/edge

See how Prerequisites are listed and summarized. Set up a Sample Project is a prerequisite and should not be repeated in each tutorial unless there are changes to the setup that need to be highlighted

2022-02-08 17:50 UTC, conneryn approved these changes

2022-02-08 18:29 UTC, nsainaney approved these changes

2022-02-08 19:26 UTC, merged