fix: lint and format all markdown files
c6o/docs pull request #143
Opened 2022-03-14 22:37 UTC by coolguy1771

Signed-off-by: Tyler Witlin <45468117+coolguy1771@users.noreply.github.com>

## Description

This fixes all of the markdown syntax and formatting inside of the CodeZero documentation to have the same consistent style. This also fixes broken links found inside of the documentation.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Technical improvement or removal of technical debt. 
- [x] Minor change: comments, documentation, trivial fixes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Unit Tests

Optional:

- [ ] Functional Tests
- [ ] Integration Tests

2022-03-18 19:24 UTC, Canuckaholic requested changes
Let's chat about these changes

2022-03-18 19:25 UTC, Canuckaholic commented on content/_sidebar.md
> +<!-- Keep the * file extensions for broken link checking -->
`<!-- Keep the *.md file extensions for broken link checking -->`

2022-03-18 19:28 UTC, Canuckaholic commented on README.md
> +# CodeZero Docs
We're using "atx" style headings, not "atx_closed

2022-03-18 19:37 UTC, coolguy1771 commented on content/_sidebar.md
> +<!-- Keep the * file extensions for broken link checking -->
It's not required anymore with lychee checking links as an action. See #142

2022-03-18 19:37 UTC, coolguy1771 commented on README.md
> +# CodeZero Docs
As I understand it the trailing # is optional in atx style headings.

2022-03-18 21:02 UTC, robblovell commented on content/_sidebar.md
> +<!-- Keep the * file extensions for broken link checking -->
Can I do local lychee checking? 

If so, please update the readme as to how to do this locally. 

If not, please leave this in so that checks can be performed prior to check in.

2022-03-18 21:03 UTC, robblovell commented on README.md
> +# CodeZero Docs
Even so, please do not use trailing hashes.  :)

2022-03-18 21:18 UTC, coolguy1771 commented on README.md
> +# CodeZero Docs
I removed all of the trailing hashes, I didn't add them.

2022-03-18 21:48 UTC, Canuckaholic commented on README.md
> +# CodeZero Docs
yes sorry my bad. I got things reversed.

2022-04-18 20:29 UTC, robblovell commented
Is this ready for review?

2022-04-28 19:28 UTC, closed without merging