fix: change format of enabled linters
c6o/docs pull request #145
Opened 2022-03-15 15:18 UTC by coolguy1771

Signed-off-by: Tyler Witlin <tyler@codezero.io>

## Description

Changes the format of the enabled linters to enable all of them.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Technical improvement or removal of technical debt. 
- [x] Minor change: comments, documentation, trivial fixes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Unit Tests

Optional:

- [ ] Functional Tests
- [ ] Integration Tests

2022-03-18 19:35 UTC, Canuckaholic requested changes
what's the reason for this format change?

2022-03-18 19:41 UTC, coolguy1771 commented
The way that megaliter parses arguments just requires it to be on one line, or else it doesn't enable any of the linters.

2022-03-18 22:45 UTC, robblovell commented on .github/workflows/megalinter.yaml
> +          ENABLE_LINTERS: ACTION_ACTIONLINT, DOCKERFILE_HADOLINT, GIT_GIT_DIFF, JSON_JSONLINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, SPELL_MISSPELL, CREDENTIALS_SECRETLINT
I think it's more readable on separate lines...

2022-03-18 22:46 UTC, robblovell requested changes
I think we should leave this "as is". To me, it's more readable on multiple lines. :)

2022-03-18 22:47 UTC, robblovell commented on .github/workflows/megalinter.yaml
> +          ENABLE_LINTERS: ACTION_ACTIONLINT, DOCKERFILE_HADOLINT, GIT_GIT_DIFF, JSON_JSONLINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, SPELL_MISSPELL, CREDENTIALS_SECRETLINT
Oh, it's required to be on one line?

2022-03-18 22:56 UTC, coolguy1771 commented on .github/workflows/megalinter.yaml
> +          ENABLE_LINTERS: ACTION_ACTIONLINT, DOCKERFILE_HADOLINT, GIT_GIT_DIFF, JSON_JSONLINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, SPELL_MISSPELL, CREDENTIALS_SECRETLINT
Yes

2022-03-18 22:56 UTC, robblovell commented on .github/workflows/megalinter.yaml
> +          ENABLE_LINTERS: ACTION_ACTIONLINT, DOCKERFILE_HADOLINT, GIT_GIT_DIFF, JSON_JSONLINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, SPELL_MISSPELL, CREDENTIALS_SECRETLINT
I see, it's a string. Have you tried `>` instead of `|-`?

2022-03-21 16:31 UTC, coolguy1771 commented on .github/workflows/megalinter.yaml
> +          ENABLE_LINTERS: ACTION_ACTIONLINT, DOCKERFILE_HADOLINT, GIT_GIT_DIFF, JSON_JSONLINT, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, SPELL_MISSPELL, CREDENTIALS_SECRETLINT
I have, it still only works with them all on one line

2022-03-24 17:51 UTC, closed without merging