chore: developing with core services.
c6o/docs pull request #151
Opened 2022-04-06 00:36 UTC by robblovell

## Description

I added a Developing Core Services tutorial as a follow-on to AJ's Developing Edge Services tutorial.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Technical improvement or removal of technical debt. 
- [ ] Minor change: comments, documentation, trivial fixes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Unit Tests

Optional:

- [ ] Functional Tests
- [ ] Integration Tests

2022-04-08 17:13 UTC, Canuckaholic requested changes
I would recommended separating out the 2 tutorials into 2 different pages. Also, please run a markdown linter on this, as there a number of issues (like missing newlines around code sections).

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +You should be able to access the local Frontend service at `http://localhost:3010/api`. You should see an api response that looks something like this:
```suggestion
You should be able to access the local Frontend service at `http://localhost:3010/api`. You should see an API response that looks something like this:
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +To intercept the sample-project-leaf service in the cluster, navigate to the url of your front end in the cluster. If you have used a load balancer, you can get the url to the frontend via a kubectl
```suggestion
To intercept the sample-project-leaf service in the cluster, navigate to the URL of your frontend in the cluster. If you have used a load balancer, you can get the URL to the frontend via a `kubectl` command:
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +You will see that the response of the leaf service is from the cluster based service:
```suggestion
You will see that the response of the leaf service is from the cluster-based service:
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +> Note: We use an extension to add headers to the request. For Chrome, the extension `ModHeader` works well.
```suggestion
> [!NOTE]
> We use an extension to add headers to the request. For Chrome, the extension `ModHeader` works well.
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +> Note: if you would like to add a teleport and run the sample-project-leaf service locally, use
```suggestion
> ![NOTE]
> if you would like to add a teleport and run the sample-project-leaf service locally, use
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +> This will allow you to listen to port 3010 locally since the cluster based service will not be using your local leaf service port.
```suggestion
> This will allow you to listen to port 3010 locally since the cluster-based service will not be using your local leaf service port.
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +> Note: When using teleport with a locally intercepted service, we need to exclude the intercept backup service at `orig-sample-project-core`
```suggestion
> ![NOTE]
> When using teleport with a locally intercepted service, we need to exclude the intercept backup service at `orig-sample-project-core`
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +Now, as with leaf services we can set up an intercept so that the frontend service talks to our locally running core service.
```suggestion
Now, as with leaf services, we can set up an intercept so that the frontend service talks to our locally running core service.
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +You can now navigate to the front end in the cloud:
```suggestion
You can now navigate to the frontend in the cloud:
```

2022-04-08 17:13 UTC, Canuckaholic commented on content/tutorials/core.md
> +Assuming the backend developer has started their core service running from the previous section on core services.
```suggestion
For the following, we are assuming the backend developer has started their core service running from the previous section on core services.
```

2022-04-18 20:27 UTC, robblovell commented on content/tutorials/core.md
> +2. Core service: Here, the developer runs _only_ a core Service which will intercept requests
I think it needs to be emphasized that the core service is run locally.

2022-04-18 20:27 UTC, robblovell commented on content/tutorials/core.md
> +1. Leaf service: Here, the developer runs _only_ a leaf Service which will intercept requests
I think it needs to be emphasized that the leaf service is run locally.

2022-04-18 23:32 UTC, Canuckaholic approved these changes

2022-04-18 23:54 UTC, merged