chore(intercept): Added header propagation instructions
c6o/docs pull request #153
Opened 2022-04-11 21:55 UTC by gburnard

fixes #3009

2022-04-12 18:17 UTC, nsainaney requested changes

2022-04-12 18:17 UTC, nsainaney commented on content/guides/commands/intercept.md
> +Unless you are intercepting *all* traffic for a particular service, the intercepted service will need receive the appropriate header in order for intercept to occur.  This is particularly important w
If you have Frontend -> Core -> Leaf, you need Core to propagate headers if you want to intercept Leaf and access it using Frontend. You don't need to do header propagation on Leaf services for example

2022-04-12 18:17 UTC, nsainaney commented on content/guides/commands/intercept.md
> +In this TypeScript example that makes an outbound call using axios, we only propagate headers that start with `x-c6o` but you should use your own convention:
```suggestion
In this TypeScript example that makes an outbound call using a REST client (axios), we only propagate headers that start with `x-c6o` but you are free to use your own convention:
```

2022-04-12 18:17 UTC, nsainaney commented on content/guides/commands/intercept.md
> +
I think this may be confusing to people who don't know Javascript (e.g. what's Object.keys and what's reduce). Maybe provide a simpler pseudocode example in addition?

2022-04-12 18:18 UTC, gburnard commented on content/guides/commands/intercept.md
> +
Okay

2022-04-12 18:19 UTC, gburnard commented on content/guides/commands/intercept.md
> +Unless you are intercepting *all* traffic for a particular service, the intercepted service will need receive the appropriate header in order for intercept to occur.  This is particularly important w
I wonder if it's smarter to advise for headr propagation between services regardless?  That way, if customers expand their architecture, they're don't need to re-think header propagation?  @nsainaney

2022-04-13 17:59 UTC, gburnard commented on content/guides/commands/intercept.md
> +
completed

2022-04-13 20:50 UTC, nsainaney requested changes

2022-04-13 20:50 UTC, nsainaney commented on content/guides/commands/intercept.md
> +Unless you are intercepting *all* traffic for a particular service, the intercepted service will need receive the appropriate header in order for intercept to occur.  This is particularly important w
```suggestion
Unless you are intercepting *all* traffic for a particular service, traffic is directed to the intercepted service in-cluster vs. local depending on HTTP headers. When the intercepted service is upstream from the frontend service, these headers need to be propagated to the intercepted service to route the traffic properly.

For example, if we have the following route Frontend -> Core -> Leaf, in order to intercept the Leaf service, the Core service has to propagate intercept headers when calling the Leaf service. 

Header propagation is commonly used for performance tracking, tracing, and other diagnostic functions.

Propagating headers is language-dependent and is not hard. It generally only requires a few lines of code.
```

2022-04-13 21:20 UTC, nsainaney approved these changes

2022-04-13 21:22 UTC, merged