Partial edit. I modified the first few sections.
c6o/docs pull request #26
Opened 2020-09-09 20:30 UTC by robblovell

Partial edit to clarify and excite!

2020-09-10 13:35 UTC, robblovell commented on content/guides/firstapp.md
> +* Applications should be well defined. Applications should not install more or less than is required for the application. If Applications require other components or other Applications to extend func
We should describe what "Application Linking" is.

2020-09-10 14:22 UTC, nsainaney requested changes

2020-09-10 14:22 UTC, nsainaney commented on content/guides/firstapp.md
> +In order to turn any Kubernetes application into a *Cloud Application*, the application needs to be published to CodeZero's Marketplace so that it can be installed and used by end users using the Cod
Just the manifest. Your application is still published to Docker and the provisioner is published to npm

2020-09-14 17:10 UTC, conneryn approved these changes

2020-09-14 17:10 UTC, conneryn commented on content/guides/firstapp.md
> +1. Write a *CodeZero Provisioner* for your application that will turn it into a CodeZero available *Cloud Application*
Should we be explicit that the provisioner needs to be published to NPM?

2020-09-14 17:12 UTC, robblovell commented on content/guides/firstapp.md
> +1. Write a *CodeZero Provisioner* for your application that will turn it into a CodeZero available *Cloud Application*
yes..

2020-09-14 18:51 UTC, conneryn commented on content/guides/firstapp.md
> +1. Publish your *Cloud Application Manifest* to NPM
The Provisioner package (not the application manifest, at least, not yet), gets published to NPM.

2020-12-24 17:54 UTC, conneryn commented
Removed myfirstapp, in favour of a AppEngine walkthrough.

2020-12-24 17:54 UTC, closed without merging