Added description of the provisioning manifest
c6o/docs pull request #29
Opened 2020-09-10 14:18 UTC by robblovell

Added description of the contents of the provisioning manifest. 

Clarifies why I should be interested, the fact that what is described below are fields not other files and the general target of the manifest within CodeZero.

2020-09-10 14:20 UTC, nsainaney submitted a review, later dismissed

2020-09-10 14:20 UTC, nsainaney commented on content/reference/appspec.md
> +Within the metadata and spec sections, there are three sub-sections each. For metadata, the sub-sections are *fields*, *labels* and *annotations*. For the spec, the sub-sections are *routes*, *provis
Allow misspelt. Does webstorm have a spell checker plugin?

2020-09-10 14:43 UTC, robblovell commented on content/reference/appspec.md
> +Within the metadata and spec sections, there are three sub-sections each. For metadata, the sub-sections are *fields*, *labels* and *annotations*. For the spec, the sub-sections are *routes*, *provis
I added https://ckeditor.com/github-writer/#:~:text=GitHub%20Writer%20is%20a%20browser,%2C%20pull%20requests%2C%20and%20wikis. It has spell check.

2020-09-12 18:52 UTC, nsainaney requested changes

2020-09-12 18:52 UTC, nsainaney commented on content/reference/appspec.md
> +The CodeZero Application's *Provisioning Manifest*, or *Custom Resource Definition* (CRD) is used by CodeZero to configure applications and provide information to the CodeZero apps for display. This
+The CodeZero Application's *Provisioning Manifest*, is a Kubernetes *Custom Resource Definition* (CRD)....

2020-09-12 18:52 UTC, nsainaney commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is used to distinguish your application components from other developer's applications |
Namespaces are logical partitions

2020-09-14 17:11 UTC, robblovell commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is used to distinguish your application components from other developer's applications |
logical partitions that do what? Do they distinguish your application from other developer's applications? Or your application from other applications?

2020-09-14 17:19 UTC, robblovell commented on content/reference/appspec.md
> +The CodeZero Application's *Provisioning Manifest*, or *Custom Resource Definition* (CRD) is used by CodeZero to configure applications and provide information to the CodeZero apps for display. This
changed the language from "or" to "is a".

2020-09-14 17:30 UTC, conneryn commented on content/reference/appspec.md
> +The CodeZero Application's *Provisioning Manifest* is a Kubernetes *Custom Resource Definition* (CRD) and is used by CodeZero to configure applications and provide information to the CodeZero apps fo
We have been calling it the "Application Manifest" in other places.  I'm not a huge fan of this terminology, and but I'm unsure if *Provisioner Manifest* is more appropriate.   Currently the CRD "kind" is "App", and it's not just about the act of provisioning the application, but rather defines the continued behaviour/existance of the app within the cluster.  For example, the manifest itself contains specs for `marina` behaviour and `routes`, not just `provisioner` details.

2020-09-14 17:37 UTC, conneryn commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is a logical parittion used to distinguish your application from other developer's applications |
The namespace is not actually intended to distinguish your application from other developers.   Except for a few special cases*, the namespace should be user-defined during installation.  The idea is, the user can choose where to install each application (ex: what folder in Marina), and additionally, they could install multiple instances of the same application.

* ask Narayan and/or Grant why/what qualifies for the special case of having hard-coded namespaces

2020-09-14 17:38 UTC, conneryn commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is used to distinguish your application components from other developer's applications |
The namespace is not actually intended to distinguish your application from other developers. Except for a few special cases*, the namespace should be user-defined during installation. The idea is, the user can choose where to install each application (ex: what folder in Marina), and additionally, they could install multiple instances of the same application.

2020-09-14 20:24 UTC, robblovell commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is used to distinguish your application components from other developer's applications |
Okay, I will take another stab at it.

2020-09-14 20:32 UTC, robblovell commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is used to distinguish your application components from other developer's applications |
This is ambiguous. I am forced to specify a "namespace" in the application manifest, but that doesn't control where in the marina the application is installed because the end user can choose a namespace and the ones specified in the manifest doesn't show up!

So, are these two different things?

2020-09-14 20:33 UTC, robblovell commented on content/reference/appspec.md
> +| namespace | Namespace where the application is installed. This is used to distinguish your application components from other developer's applications |
Is it true that the application manifest does nothing? 

Oh, fuck... Right, the application manifest is a template that is used when the end user specifies a namespace... Duh...

2020-12-24 17:56 UTC, conneryn commented
Removed explicit documentation about appspec, as developers should focus on Application Manifest instead.

2020-12-24 17:56 UTC, closed without merging