feat: First Draft of the Dashboard App documentation
c6o/docs pull request #98
Opened 2021-12-02 00:53 UTC by robblovell

## Description

Documentation for the Dashboard App.

2021-12-02 17:13 UTC, nsainaney submitted a review, later dismissed

2021-12-02 17:13 UTC, nsainaney commented on content/guides/usage/adding-a-workspace.md
> +the dashboard menu. This will find the Codezero Development Profiles within the .codezero/develop directory of the
Not sure if we discussed this but my preference would be that we support

codezero
.codezero

The dot creates a hidden folder and there's no reason this folder should be hidden.


I would also prefer the abbreviation c6o bu am fine with the long form

2021-12-02 17:13 UTC, nsainaney commented on content/guides/usage/creating-a-dev-profile.md
> +A development profile is created through running CLI commands with a --save-profile flag:
Add development profie section to concepts

2021-12-02 17:13 UTC, nsainaney commented on content/guides/usage/creating-a-dev-profile.md
> +Commands can be added by running another command and saving to the same profile. The CLI will ask you if you are
We need a --append-profile flag as we need to be able to run commands without prompts

2021-12-02 17:13 UTC, nsainaney commented on content/guides/usage/creating-a-dev-profile.md
> +apiVersion: system.codezero.io/v1alpha1
Profiles are subject to change. They should be treated as opaque files at this time. I'm not sure we want people to tinker with them

2021-12-02 18:15 UTC, robblovell commented on content/guides/usage/creating-a-dev-profile.md
> +Commands can be added by running another command and saving to the same profile. The CLI will ask you if you are
We need to document the "save-profile-mode" flag that takes as options "create", "append", or "replace".

2021-12-02 18:19 UTC, robblovell commented on content/guides/usage/adding-a-workspace.md
> +the dashboard menu. This will find the Codezero Development Profiles within the .codezero/develop directory of the
feature added to the board.

2021-12-02 18:20 UTC, nsainaney commented on content/guides/usage/creating-a-dev-profile.md
> +Commands can be added by running another command and saving to the same profile. The CLI will ask you if you are
I would recommend keeping it simple:

```
--save-profile <file>
--append-profile <file>

--save-profile <file> --force
OR
--replace-profile <file>
```

2021-12-02 18:28 UTC, robblovell commented on content/guides/usage/creating-a-dev-profile.md
> +Commands can be added by running another command and saving to the same profile. The CLI will ask you if you are
docs updated..

2021-12-02 18:29 UTC, robblovell commented on content/guides/usage/creating-a-dev-profile.md
> +apiVersion: system.codezero.io/v1alpha1
removed visible information on the content of the dev profile.

2021-12-02 18:52 UTC, robblovell commented on content/guides/usage/creating-a-dev-profile.md
> +A development profile is created through running CLI commands with a --save-profile flag:
added.

2022-01-05 18:15 UTC, Canuckaholic requested changes

2022-01-05 18:15 UTC, Canuckaholic commented on content/concepts/profiles.md
> +A development profile remembers the parameters required so that the developer doesn't have to remember the parameters
```suggestion
A development profile records the specifications for running one ore more commands so that the developer doesn't have to remember all of the required parameters
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/guides/development-profiles-with-mount.md
> +A development profile remembers the parameters required so that the developer doesn't have to remember the parameters
```suggestion
A development profile records the specifications for running one ore more commands so that the developer doesn't have to remember all of the required parameters
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/guides/usage/running-a-dev-profile.md
> +Development Profiles are read from the .codezero/develop directory and contain instructions to startup various CodeZero commands.
```suggestion
Development Profiles are read from the `.codezero/develop` directory and contain instructions to startup various CodeZero commands.
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/guides/using-dashboard.md
> +3. Manage your user profile and how you appear to other developers
```suggestion
1. Manage Kubernetes configuration files to access and switch between clusters.
2. Access, run, and manage CodeZero development profiles within CodeZero workspaces.
3. Manage your user profile and how you appear to other developers.
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/references/development-profile.md
> +A development profile is created through running CLI commands with a --save-profile flag:
```suggestion
A development profile is created by running CLI commands with a --save-profile flag:
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/references/development-profile.md
> +> The namespaceResourceId and resourceQuery sections of the development profile above are note needed.
```suggestion
> The namespaceResourceId and resourceQuery sections of the development profile above are not needed.
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/references/development-profile.md
> +? This profile already exists.  What would you like to do with the existing profile? append
```suggestion
? This profile already exists. What would you like to do with the existing profile? append
```

2022-01-05 18:15 UTC, Canuckaholic commented on content/references/development-profile.md
> +`namespaceResourceId`, and `resourceQuery` to the following:
```suggestion
If you wish to manually edit this file, it can be simplified by removing `version`, `output`, 
`namespaceResourceId`, and `resourceQuery` as they are not required to run the development profile.
```

2022-01-08 03:40 UTC, Canuckaholic approved these changes

2022-01-08 03:45 UTC, merged